name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/release.yaml"
      - "*.tf"
      - "*.md"

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write

    name: Release
    runs-on: ubuntu-latest
    # Skip running release workflow on forks
    if: github.repository_owner == 'jhulndev'
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Release
        uses: cycjimmy/semantic-release-action@b1b432f13acb7768e0c8efdec416d363a57546f2 # v4.1.1
        with:
          semantic_version: 24.2.3
          extra_plugins: |
            conventional-changelog-conventionalcommits@8.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
